/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChatHistoryRouteImport } from './routes/api/chat-history'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiReceiptRouteImport } from './routes/api/receipt'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiExpensesIdRouteImport } from './routes/api/expenses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatHistoryRoute = ApiChatHistoryRouteImport.update({
  id: '/api/chat-history',
  path: '/api/chat-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptRoute = ApiReceiptRouteImport.update({
  id: '/api/receipt',
  path: '/api/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesIdRoute = ApiExpensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExpensesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-history': typeof ApiChatHistoryRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/receipt': typeof ApiReceiptRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-history': typeof ApiChatHistoryRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/receipt': typeof ApiReceiptRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-history': typeof ApiChatHistoryRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/receipt': typeof ApiReceiptRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-history'
    | '/api/expenses'
    | '/api/health'
    | '/api/profile'
    | '/api/receipt'
    | '/api/stats'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/expenses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-history'
    | '/api/expenses'
    | '/api/health'
    | '/api/profile'
    | '/api/receipt'
    | '/api/stats'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/expenses/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-history'
    | '/api/expenses'
    | '/api/health'
    | '/api/profile'
    | '/api/receipt'
    | '/api/stats'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/expenses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatHistoryRoute: typeof ApiChatHistoryRoute
  ApiExpensesRoute: typeof ApiExpensesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiReceiptRoute: typeof ApiReceiptRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-history': {
      id: '/api/chat-history'
      path: '/api/chat-history'
      fullPath: '/api/chat-history'
      preLoaderRoute: typeof ApiChatHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipt': {
      id: '/api/receipt'
      path: '/api/receipt'
      fullPath: '/api/receipt'
      preLoaderRoute: typeof ApiReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/$id': {
      id: '/api/expenses/$id'
      path: '/$id'
      fullPath: '/api/expenses/$id'
      preLoaderRoute: typeof ApiExpensesIdRouteImport
      parentRoute: typeof ApiExpensesRoute
    }
  }
}

interface ApiExpensesRouteChildren {
  ApiExpensesIdRoute: typeof ApiExpensesIdRoute
}

const ApiExpensesRouteChildren: ApiExpensesRouteChildren = {
  ApiExpensesIdRoute: ApiExpensesIdRoute,
}

const ApiExpensesRouteWithChildren = ApiExpensesRoute._addFileChildren(
  ApiExpensesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatHistoryRoute: ApiChatHistoryRoute,
  ApiExpensesRoute: ApiExpensesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiReceiptRoute: ApiReceiptRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
